### ISSUE TITLE
전체 피드백 

### ISSUE THREAD

**Issue by dpudpu** [1-sunshine/miniprojects-2019#41]
- 자기 피드에 글이 안써짐

- 자기 페이지에 내 글이 안나온다.

- nav에 자기 이름 여러번 클릭시 404 에러 발생

- 프로필 수정시 성, 이름이 합쳐서 나온다.

- 글을 개행해서 작성해도 적용이 안된다.

- 프로필 수정 하고 실패하면 다시 수정 창을 누르면 비밀번호가 그대로 남아있다.

- 큰 동영상 처리할 때 에러메시지를 띄어주던지 과정 진행중이라고 표시를 해주면 좋겠다. (동영상에 1.5기가 올림)

-  수정하면 글이 추가로 써진다. 

- 대댓글 입력 후에 대댓글 입력창이 사라지지 않음

- 대댓글 보기가 없다

- 검색창에서 nav에 있는 자기 아이디 클릭하면 404 에러 

- 답글 열려 있는 상태에서 댓글 쓰면 답글이 사라진다.

**Comment by hyunssooo** [comment]
게시글 수정 재현이 안되는데 정확한 상황을 알 수 있을까요?? :)

**Comment by oeeen** [comment]
감사합니다 close 하겠습니다.
